//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSUMA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=SumaLealtadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Channel> Channels { get; set; }
        public DbSet<CIUDAD> CIUDADES { get; set; }
        public DbSet<Civil_Status> Civil_Statuses { get; set; }
        public DbSet<ESTADO> ESTADOS { get; set; }
        public DbSet<Interest> Interests { get; set; }
        public DbSet<MUNICIPIO> MUNICIPIOS { get; set; }
        public DbSet<Nacionality> Nacionalities { get; set; }
        public DbSet<PAIS> PAISES { get; set; }
        public DbSet<PAIS_ESTADO> PAIS_ESTADOS { get; set; }
        public DbSet<PARROQUIA> PARROQUIAS { get; set; }
        public DbSet<Sex> Sexes { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<URBANIZACION> URBANIZACIONES { get; set; }
    }
}
